kubeProxyReplacement: strict
k8sServiceHost: 172.18.0.3 # use master node in kind network
k8sServicePort: 6443       # use api server port
#hostServices:
#  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
image:
  pullPolicy: IfNotPresent
ingressController:
  enabled: true
ipam:
  mode: kubernetes
hubble:
  enabled: true
  relay:
    enabled: true
securityContext:
  privileged: true
cluster:
  id: 0
  name: kind-cilium-workshop
encryption:
  nodeEncryption: false
operator:
  replicas: 1
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnel: vxlan
